In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("alitaqishah/pakistan-economic-indicators-2000-2025")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/alitaqishah/pakistan-economic-indicators-2000-2025/1.archive...

100%|██████████| 2.53k/2.53k [00:00<00:00, 3.93MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/alitaqishah/pakistan-economic-indicators-2000-2025/versions/1

In [3]:
import pandas as pd
import os

# List files in the downloaded directory to find the CSV file
files_in_path = os.listdir(path)
csv_file = None
for f in files_in_path:
    if f.endswith('.csv'):
        csv_file = f
        break

if csv_file:
    full_csv_path = os.path.join(path, csv_file)
    df = pd.read_csv(full_csv_path)
    print(f"Successfully loaded {csv_file} into DataFrame.")
    display(df.head())
else:
    print(f"No CSV file found in {path}")

Successfully loaded pakistan_economic_indicators_2000_2025.csv into DataFrame.

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.9,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.0,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.1,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.7,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.4,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s

LOADING FIRST 20 ROWS

In [4]:
df.head(20)

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.9,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.0,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.1,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.7,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.4,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.0,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.8,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.8,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.0,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.6,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.6,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.6,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.4,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.7,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.1,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.1,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.5,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.2,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.8,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.9,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    26 non-null     int64
 1   gdp_usd_bn              26 non-null     float64
 2   gdp_growth_pct          26 non-null     float64
 3   gdp_per_capita_usd      26 non-null     int64
 4   inflation_cpi_pct       26 non-null     float64
 5   unemployment_pct        26 non-null     float64
 6   remittances_usd_bn      26 non-null     float64
 7   exports_usd_bn          26 non-null     float64
 8   imports_usd_bn          26 non-null     float64
 9   trade_balance_usd_bn    26 non-null     float64
 10  forex_reserves_usd_bn   26 non-null     float64
 11  policy_rate_pct         26 non-null     float64
 12  pkr_per_usd             26 non-null     float64
 13  public_debt_gdp_pct     26 non-null     float64
 14  current_account_usd_bn  26 non-null     float64
 15  fdi_inflows_usd_bn      26 non-null     float64
 16  population_mn           26 non-null     float64
 17  literacy_rate_pct       26 non-null     float64
 18  agriculture_gdp_pct     26 non-null     float64
 19  services_gdp_pct        26 non-null     float64
 20  industry_gdp_pct        26 non-null     float64
 21  tax_revenue_gdp_pct     26 non-null     float64
 22  mobile_per_100          26 non-null     float64
 23  imf_program_active      26 non-null     int64
 24  key_events              26 non-null     object
 25  remittances_gdp_pct     26 non-null     float64
 26  exports_gdp_pct         26 non-null     float64
 27  imports_gdp_pct         26 non-null     float64
 28  fdi_gdp_pct             26 non-null     float64
 29  gdp_growth_category     26 non-null     object
 30  inflation_category      26 non-null     object
 31  decade                  26 non-null     object
 32  population_million      26 non-null     float64
dtypes: float64(26), int64(3), object(4)
memory usage: 6.8+ KB

In [8]:
df.describe()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,services_gdp_pct,industry_gdp_pct,tax_revenue_gdp_pct,mobile_per_100,imf_program_active,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,population_million
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,...,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,2012.500000,233.084615,4.110000,1012.153846,9.361538,6.261538,14.866538,21.453846,39.853846,-18.400000,...,51.834615,25.726923,11.273077,55.546154,0.423077,5.504231,9.543077,16.530769,0.976538,221.843846
std,7.648529,92.279119,2.195969,258.434161,6.431739,1.059085,10.775681,6.914809,18.568494,12.195934,...,1.909543,0.944270,1.422549,30.772471,0.503831,2.481398,1.360852,3.465463,0.807802,36.945292
min,2000.000000,99.900000,-0.500000,614.000000,2.900000,4.500000,1.080000,9.200000,10.300000,-47.600000,...,47.200000,24.300000,9.100000,0.300000,0.000000,1.080000,7.210000,10.130000,0.310000,160.100000
25%,2006.250000,156.300000,2.700000,807.000000,4.650000,5.650000,5.375000,17.775000,29.075000,-22.775000,...,51.175000,25.025000,10.225000,39.650000,0.000000,3.370000,8.515000,14.877500,0.510000,192.897500
50%,2012.500000,243.350000,4.100000,1040.500000,7.750000,6.000000,13.555000,22.000000,44.100000,-20.250000,...,52.300000,25.650000,10.850000,70.450000,0.000000,5.570000,9.285000,16.985000,0.745000,220.610000
75%,2018.750000,299.375000,5.650000,1226.000000,11.200000,6.475000,21.935000,24.800000,48.475000,-11.300000,...,53.075000,26.350000,12.350000,76.900000,1.000000,7.112500,10.555000,19.205000,0.955000,252.565000
max,2025.000000,390.000000,9.000000,1393.000000,29.200000,8.300000,38.000000,34.000000,80.000000,-0.500000,...,54.100000,27.700000,14.500000,87.000000,1.000000,9.740000,12.200000,21.250000,3.330000,280.580000

In [10]:
df.isnull().sum()

year                      0
gdp_usd_bn                0
gdp_growth_pct            0
gdp_per_capita_usd        0
inflation_cpi_pct         0
unemployment_pct          0
remittances_usd_bn        0
exports_usd_bn            0
imports_usd_bn            0
trade_balance_usd_bn      0
forex_reserves_usd_bn     0
policy_rate_pct           0
pkr_per_usd               0
public_debt_gdp_pct       0
current_account_usd_bn    0
fdi_inflows_usd_bn        0
population_mn             0
literacy_rate_pct         0
agriculture_gdp_pct       0
services_gdp_pct          0
industry_gdp_pct          0
tax_revenue_gdp_pct       0
mobile_per_100            0
imf_program_active        0
key_events                0
remittances_gdp_pct       0
exports_gdp_pct           0
imports_gdp_pct           0
fdi_gdp_pct               0
gdp_growth_category       0
inflation_category        0
decade                    0
population_million        0
dtype: int64

### 1. What was the average GDP growth rate (`gdp_growth_pct`) per decade?

In [11]:
# Group by 'decade' and calculate the mean of 'gdp_growth_pct'
avg_gdp_growth_per_decade = df.groupby('decade')['gdp_growth_pct'].mean().reset_index()
print("Average GDP Growth Rate per Decade:")
display(avg_gdp_growth_per_decade)

Average GDP Growth Rate per Decade:

  decade  gdp_growth_pct
0  2000s        5.030000
1  2010s        3.990000
2  2020s        2.776667

### 2. Which year had the highest inflation rate (`inflation_cpi_pct`)?

In [12]:
# Find the row with the maximum 'inflation_cpi_pct'
highest_inflation_year = df.loc[df['inflation_cpi_pct'].idxmax(), ['year', 'inflation_cpi_pct']]
print("Year with the Highest Inflation Rate:")
display(highest_inflation_year)

Year with the Highest Inflation Rate:

year                 2023
inflation_cpi_pct    29.2
Name: 23, dtype: object

### 3. How has the unemployment rate (`unemployment_pct`) trended over time?

In [13]:
# Select 'year' and 'unemployment_pct' and sort by year
unemployment_trend = df[['year', 'unemployment_pct']].sort_values(by='year').reset_index(drop=True)
print("Unemployment Rate Trend Over Time:")
display(unemployment_trend)

Unemployment Rate Trend Over Time:

    year  unemployment_pct
0   2000               7.8
1   2001               7.8
2   2002               8.3
3   2003               8.3
4   2004               7.7
5   2005               7.7
6   2006               6.2
7   2007               5.2
8   2008               5.2
9   2009               5.5
10  2010               5.6
11  2011               6.0
12  2012               6.0
13  2013               6.2
14  2014               6.0
15  2015               5.9
16  2016               5.9
17  2017               5.8
18  2018               5.8
19  2019               4.5
20  2020               4.6
21  2021               6.3
22  2022               6.2
23  2023               6.5
24  2024               6.4
25  2025               5.4

4. Which year recorded the largest trade deficit (most negative `trade_balance_usd_bn`)?

In [16]:
# Find the row with the minimum (most negative) 'trade_balance_usd_bn'
largest_trade_deficit = df.loc[df['trade_balance_usd_bn'].idxmin(), ['year', 'trade_balance_usd_bn']]
print("Year with the Largest Trade Deficit:")
display(largest_trade_deficit)

Year with the Largest Trade Deficit:

year                    2022
trade_balance_usd_bn   -47.6
Name: 22, dtype: object

### 5. How many years fall into each `gdp_growth_category`?

In [17]:
# Use value_counts() on the 'gdp_growth_category' column
gdp_growth_counts = df['gdp_growth_category'].value_counts().reset_index()
gdp_growth_counts.columns = ['GDP Growth Category', 'Number of Years']
print("Number of Years per GDP Growth Category:")
display(gdp_growth_counts)

Number of Years per GDP Growth Category:

  GDP Growth Category  Number of Years
0     Moderate Growth               14
1          Low Growth                6
2         High Growth                4
3  Recession/Negative                2

### 6. What are the top 3 years with the highest foreign exchange reserves (`forex_reserves_usd_bn`)?

In [18]:
# Sort by 'forex_reserves_usd_bn' in descending order and take the top 3
top_forex_reserves = df.nlargest(3, 'forex_reserves_usd_bn')[['year', 'forex_reserves_usd_bn']]
print("Top 3 Years with Highest Foreign Exchange Reserves:")
display(top_forex_reserves)

Top 3 Years with Highest Foreign Exchange Reserves:

    year  forex_reserves_usd_bn
16  2016                   23.1
21  2021                   22.8
17  2017                   21.4

### 7. What is the highest literacy rate (`literacy_rate_pct`) recorded in the dataset?

In [20]:
# Find the maximum value in the 'literacy_rate_pct' column
highest_literacy_rate = df['literacy_rate_pct'].max()
print(f"The highest literacy rate recorded is: {highest_literacy_rate:.2f}%")

The highest literacy rate recorded is: 64.00%

### 8. What is the average PKR to USD exchange rate (`pkr_per_usd`) across all years?

In [21]:
# Calculate the mean of the 'pkr_per_usd' column
average_exchange_rate = df['pkr_per_usd'].mean()
print(f"The average PKR to USD exchange rate is: {average_exchange_rate:.2f}")

The average PKR to USD exchange rate is: 115.18